version: "3.7"

services:
  database_mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    network_mode: host
  app:
    build: ./backend
    container_name: backend
    ports:
      - 3333:3333
    volumes:
      - ./backend:/usr/app/
    network_mode: host
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/usr/app
    network_mode: host
  redis:
    image: redis
    command: redis-server --requirepass meaprovazoox
    ports:
      - 6379:6379
    network_mode: host
